name: pkg test
on:
  push:
    # branches: [main, release/*, develop]
    tags:
      - '**'

  workflow_dispatch:

jobs:

  build_deb_package:
    name: Build deb packages
    runs-on: ubuntu-latest
    container:
      image: legleux/rippled-builder:10-06-23
    env:
      PKG: deb
    steps:
      - name: Install git
        run: |
          ulimit -n 1024000 && yum -y update
          source /opt/rh/devtoolset-11/enable
          yum install -y curl-devel expat-devel gettext-devel openssl-devel zlib-devel perl-CPAN perl-devel
          cd /tmp/ && mkdir git && cd git
          wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.42.0.tar.gz
          tar -xvf git-2.42.0.tar.gz # --strip-components=1 # ?
          cd git-2.42.0

          make configure
          ./configure --prefix=/usr/local
          make -j $(nproc)
          make install
          git --version

      - name: Get Clio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build_package
        name: Test pkg step

      - name: check for tag
        run: |
          git config --global --add safe.directory /__w/test_action/test_action
          git tag --points-at HEAD
  # build_rpm_package:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: legleux/rippled-builder:10-06-23
  #   env:
  #     PKG: rpm
  #   steps:
  #     - name: Get Clio
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
