name: pkg test
on:
  push:
    # branches: [main, release/*, develop]
    tags:
      - '**'

  workflow_dispatch:

jobs:

  build_deb_package:
    name: Build deb packages
    runs-on: ubuntu-latest
    container:
      image: legleux/rippled-builder:10-06-23
    env:
      PKG: deb
    steps:
      - name: Install git
        uses: ./.github/actions/update_git

      - name: Get Clio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build_package
        name: Test pkg step

      - name: check for tag
        run: |
          git config --global --add safe.directory /__w/test_action/test_action
          TAG=$(git tag --points-at HEAD)
          echo "TAG is $TAG"
  # build_rpm_package:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: legleux/rippled-builder:10-06-23
  #   env:
  #     PKG: rpm
  #   steps:
  #     - name: Get Clio
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
