name: nix
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'docker image'
        required: false
        default: 'warning'
        type: choice
        options:
          - ubuntu:20.04
          - ubuntu:18.04
          - ubuntu:22.04

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dependencies:
    name: "Dependencies"
    strategy:
      matrix:
        platform:
          - linux
        compiler:
          - gcc
          - clang
        configuration:
          - Debug
          - Release
        include:
          - compiler: gcc
            profile:
              version: 11
              cc: /usr/bin/gcc
              cxx: /usr/bin/g++
          - compiler: clang
            profile:
              version: 14
              cc: /usr/bin/clang-14
              cxx: /usr/bin/clang++-14
    runs-on: ${{ github.event.inputs.image }}"

    steps:
      - name: Run stuff
        run: |
          echo neat ${{ matrix.compiler }} ${{ matrix.configuration }} ${{ matrix.include }}
          echo ${{ matrix }}
